version: '3.1'

services:
  db:
    image: mysql:8.0.31
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gerenciador-projetos

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8000:80